name: Run Cypress Tests with Mochawesome Report

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests headlessly
        run: npx cypress run

      - name: Generate Mochawesome report
        if: always()
        run: |
          npx mochawesome-merge cypress/reports/*.json -o cypress/reports/merged-report.json
          npx marge cypress/reports/merged-report.json --reportDir cypress/reports --reportFilename index.html

      - name: Upload Cypress Report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-report
          path: cypress/reports/index.html
